# A script for running all the tests 
include(joinpath(@__DIR__,"..\\include.jl"))

println("test 1")
include(joinpath(@__DIR__,"test1_batch_linear","test1.jl"))
println("test 2")
include(joinpath(@__DIR__,"test2_2column_linear","test_linear_2columns.jl"))
println("test 3")
include(joinpath(@__DIR__,"test3_LWE","LWE.jl"))
println("test 4")
include(joinpath(@__DIR__,"test4_SMB","SMB_LRM_Langmuir.jl"))
println("test 5")
include(joinpath(@__DIR__,"test5_batch_lrmp_langmuir","test5.jl"))
println("test 6")
include(joinpath(@__DIR__,"test6_grm_linear","test6.jl"))
println("test 8")
include(joinpath(@__DIR__,"test8_cstr","test8.jl"))
println("test 9")
include(joinpath(@__DIR__,"test9_cstr_col_cstr","test9.jl"))
